#!/bin/sh

set -e

echo "removing all DTR containers"
docker ps -a --format "{{.Image }} {{.Names}}" | grep trusted-registry | sed "s/.* //"
docker rm $(docker ps -a --format "{{.Image }} {{.Names}}" | grep trusted-registry | sed "s/.* //") || true

echo "removing all DTR images"
docker images -a --format "{{.Repository}}:{{.Tag}}" | grep 
docker rmi $(docker images -a --format "{{.Repository}}:{{.Tag}}" | grep trusted-registry) || true

echo "removing all DTR volumes"
docker volume ls -q | grep trusted-registry
docker volume rm $(docker volume ls -q | grep trusted-registry)
