#!/bin/sh

BASEDIR=$(dirname "$0")
echo ""
echo "Please start this container with the following parameters:"
echo ""
echo "   docker run --rm -it -v \"/:/host\" <installer-image> $@"
echo ""
echo " this installer supports the following commands:"
ls $BASEDIR | sed "s/\(.*\)/      \1/g"


