#!/bin/sh

set -e

echo "DTR containers:"
docker ps -a --format "{{.Image }} {{.Names}}" | grep trusted-registry | sed "s/.* //"

echo
echo "DTR images"
docker images -a --format "{{.Repository}}:{{.Tag}}" | grep trusted-registry
